kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: demo-ia-ops
nodes:
  - role: control-plane
    extraPortMappings:
      # demo-app NodePort → http://localhost:8081
      - containerPort: 30081
        hostPort: 8081
        listenAddress: "0.0.0.0"
        protocol: TCP
      # ArgoCD NodePort → https://localhost:8080
      - containerPort: 30080
        hostPort: 8080
        listenAddress: "0.0.0.0"
        protocol: TCP
